import { dom, library } from '@fortawesome/fontawesome-svg-core';
import {faGithub} from '@fortawesome/free-brands-svg-icons';
import {
    faBell,
    faCalendar as faRegularCalendar,
    faCircleCheck,
    faCircleXmark,
    faClock,
    faComment as faRegularComment,
    faEnvelopeOpen,
    faEye,
    faFileExcel,
    faFileLines,
    faFilePdf,
    faFileZipper,
    faFolderOpen,
    faPaperPlane,
    faPenToSquare,
    faRectangleList as faRegularRectangleList,
    faSquare,
    faSquareCheck,
    faTrashCan,
    faUser,
} from '@fortawesome/free-regular-svg-icons';
import {
    faArrowDown,
    faArrowDownWideShort,
    faArrowRight,
    faArrowUp,
    faBuildingColumns,
    faCalendar,
    faCampground,
    faCar,
    faCheck,
    faCircleInfo,
    faCog,
    faComment,
    faDownload,
    faFileContract,
    faFileInvoiceDollar,
    faFlask,
    faForwardStep,
    faLock,
    faMagnifyingGlass,
    faPenRuler,
    faPlus,
    faPrint,
    faRectangleList,
    faRightLeft,
    faRoute,
    faSort,
    faSortDown,
    faSortUp,
    faUserGraduate,
    faUsers,
    faXmark,
} from '@fortawesome/free-solid-svg-icons';

library.add(
    faArrowDown,
    faArrowDownWideShort,
    faArrowRight,
    faArrowUp,
    faBell,
    faBuildingColumns,
    faCalendar,
    faCampground,
    faCar,
    faCheck,
    faCircleCheck,
    faCircleInfo,
    faCircleXmark,
    faClock,
    faCog,
    faComment,
    faDownload,
    faEnvelopeOpen,
    faEye,
    faFileContract,
    faFileExcel,
    faFileInvoiceDollar,
    faFileLines,
    faFilePdf,
    faFileZipper,
    faFlask,
    faFolderOpen,
    faForwardStep,
    faGithub,
    faLock,
    faMagnifyingGlass,
    faPaperPlane,
    faPenRuler,
    faPenToSquare,
    faPlus,
    faPrint,
    faRectangleList,
    faRegularCalendar,
    faRegularComment,
    faRegularRectangleList,
    faRightLeft,
    faRoute,
    faSort,
    faSortDown,
    faSortUp,
    faSquare,
    faSquareCheck,
    faTrashCan,
    faUser,
    faUserGraduate,
    faUsers,
    faXmark,
);

export { dom };
