<?php

abstract class BasePresenter extends Nette\Application\UI\Presenter {

    protected function startup() {
        parent::startup();
        // Zapnutí session (pokud neběží)
//        if (!$this->context->session->isStarted()) {
//            $this->context->session->start();
//        }
        \Extras\Debug\RequestsPanel::register();

        $this->template->backlink = $this->getParameter("backlink");

//        if (!function_exists("FormContainer_addDatePicker")) {
            \Nette\Forms\Container::extensionMethod('addDatePicker', function (\Nette\Forms\Container $container, $name, $label = NULL) {
                        return $container[$name] = new JanTvrdik\Components\DatePicker($label);
                    });
//            FormContainer::extensionMethod('Form::addDatePicker', 'FormContainer_addDatePicker');
//        }
        if ($this->user->isLoggedIn() && $this->context->userService->isLoggedIn()) //prodluzuje přihlášení při každém požadavku
            $this->context->authService->updateLogoutTime();
    }

    protected function beforeRender() {
        parent::beforeRender();
        if ($this->user->isLoggedIn()) {
            $this->template->myRoles = $this->context->userService->getAllSkautISRoles();
            $this->template->myRole = $this->context->userService->getRoleId();
        }
//        $this->template->cntActiveEvents = $this->context->eventService->event->getCountOfActiveEvents();
    }

    //upravuje roli ve skautISu
    public function handleChangeRole($roleId) {
        $this->context->userService->updateSkautISRole($roleId);
        $this->redirect("this");
    }

//    public function createComponentCss()
//{
//    return new \WebLoader\Nette\CssLoader(
//        $this->context->webloader->cssDefaultCompiler, // service generated by extension
//        $this->template->basePath . '/webtemp'
//    );
//}

    public function createComponentCss() {
        $files = new WebLoader\FileCollection(WWW_DIR . '/css');
        $compiler = WebLoader\Compiler::createCssCompiler($files, WWW_DIR . '/webtemp');

        //s minimalizací zlobí bootstrap
//        $compiler->addFilter(new VariablesFilter(array('foo' => 'bar')));        
//        function mini($code) {
//            return CssMin::minify($code);
//        }
//        $compiler->addFilter("mini");
        $control = new WebLoader\Nette\CssLoader($compiler, $this->context->httpRequest->url->baseUrl . 'webtemp');
        $control->setMedia('screen');

        return $control;
    }

    public function createComponentJs() {
        $files = new WebLoader\FileCollection(WWW_DIR . '/js');
        $compiler = WebLoader\Compiler::createJsCompiler($files, WWW_DIR . '/webtemp');
        return new WebLoader\Nette\JavaScriptLoader($compiler, $this->context->httpRequest->url->baseUrl . 'webtemp');
    }

}
