networks:
    ci:

volumes:
    ci-log:
    ci-uploads:
    ci-temp:
    ci-codeception-output:
    ci-codeception-generated:
    ci-webtemp:

services:
    php-test:
        image: ${COMPOSE_PROJECT_NAME:-hskauting-ci}-php-test
        build:
            context: ..
            dockerfile: docker/containers/php/Dockerfile.ci
            args:
                CI_INPUTS_PREPARED: ${CI_INPUTS_PREPARED:-0}
        working_dir: /app
        shm_size: 1g
        user: root
        command: ["php-fpm", "-R"]
        env_file:
            - ./containers/php/ini/image.ini
        environment:
            APP_ENV: ci
            HEADLESS: ${HEADLESS:-}
        networks:
            - ci
        volumes:
            - ../vendor:/app/vendor:ro
            - ci-log:/app/log
            - ci-uploads:/app/uploads
            - ci-temp:/app/temp
            - ci-codeception-output:/app/tests/_output
            - ci-codeception-generated:/app/tests/_support/_generated
            - ci-webtemp:/app/www/webtemp

    mysql-test:
        image: mysql:8.0
        environment:
            MYSQL_DATABASE: ${DB_NAME:-hskauting}
            MYSQL_USER: ${DB_USER:-hskauting}
            MYSQL_PASSWORD: ${DB_PASSWORD:-hskauting}
            MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD:-root}
            MYSQL_COLLATION: utf8mb3_czech_ci
            MYSQL_CHARACTER_SET: utf8mb3
        networks:
            - ci
        volumes:
            - ./containers/mysql-test/my.cnf:/etc/mysql/conf.d/my.cnf:ro
        tmpfs:
            - /var/lib/mysql
        command:
            - mysqld
            - --innodb-flush-log-at-trx-commit=0
            - --sync-binlog=0
            - --innodb-use-native-aio=0

    nginx:
        image: ${COMPOSE_PROJECT_NAME:-hskauting-ci}-nginx
        build:
            context: ./containers/nginx
            dockerfile: Dockerfile.ci
            additional_contexts:
                application: service:php-test
        restart: !reset null
        working_dir: !reset null
        userns_mode: !reset null
        hostname: !reset null
        labels: !reset {}
        volumes: !reset []
        depends_on: !override
            - php-test
        networks: !override
            ci:
                aliases:
                    - moje-hospodareni.cz

    selenium:
        image: selenium/standalone-chrome
        shm_size: 2g
        environment:
            SE_VNC_NO_PASSWORD: 1
            SE_NODE_SESSION_TIMEOUT: 900
            SCREEN_WIDTH: 1920
            SCREEN_HEIGHT: 1080
        networks:
            - ci

    gotenberg:
        image: gotenberg/gotenberg:8
        restart: !reset null
        command:
            - gotenberg
            - --chromium-disable-javascript=true
            - --chromium-allow-list=file:///tmp/.*
        networks: !override
            - ci
