Model\Travel\Command\Travel:

    type: entity
    inheritanceType: SINGLE_TABLE
    table: tc_travels

    id:
        command: { associationKey: true }
        id: { type: integer }

    discriminatorColumn:
        name: has_fuel
        type: smallint
    discriminatorMap:
        "1": Model\Travel\Command\VehicleTravel
        "0": Model\Travel\Command\TransportTravel

    manyToOne:
        command:
            targetEntity: Model\Travel\Command
            joinColumn:
                name: command_id
                referencedColumnName: id
            inversedBy: travels

    embedded:
        details:
            class: Model\Travel\Command\TravelDetails
            columnPrefix: false
