name: Deploy template

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
      root_dir:
        required: true
        type: string
      ssh_username:
        required: true
        type: string
      host:
        required: true
        type: string
      port:
        required: false
        type: string
        default: "22"
    secrets:
      DEPLOY_SSH_KEY:
        required: true

jobs:
  deploy:
    runs-on: ubuntu-22.04
    # Required GitHub Environment vars:
    # APP_ENV, APP_BASE_URL, SEND_EMAIL, DB_HOST, DB_NAME, DB_USER
    # Optional GitHub Environment vars:
    # SKAUTIS_TEST_MODE, TEST_BACKGROUND, TRACY_SHOW_BAR, GOOGLE_CREDENTIALS_FILE
    # Required GitHub Environment secrets:
    # APPLICATION_ID, DB_FIX_TOKEN_SHA256, DB_PASSWORD, GOOGLE_CREDENTIALS
    # Optional GitHub Environment secret:
    # SENTRY_DSN
    environment: ${{ inputs.environment }}
    container:
      image: webwingscz/lebeda-deployer-php82
    steps:
      - name: Download workdir
        uses: actions/download-artifact@v7
        with:
          name: workdir
          path: .
      - name: Extract workdir
        run: tar -xzpf workdir.tar.gz
      - name: Run deploy
        run: |
          mkdir -p ~/.ssh && chmod 700 ~/.ssh
          eval $(ssh-agent -s)
          echo "$PRIVATE_KEY" | tr -d '\r' | ssh-add -
          dep deploy:ssh_warmup ${{ inputs.environment }} -f /app/deploy.php -vvv          
          echo "Waiting for container to initialize..."
          sleep 10        
          dep deploy ${{ inputs.environment }} -f /app/deploy.php -vvv
        env:
          PRIVATE_KEY: ${{ secrets.DEPLOY_SSH_KEY }}
          ROOT_DIR: ${{ inputs.root_dir }}
          SSH_USERNAME: ${{ inputs.ssh_username }}
          HOST: ${{ inputs.host }}
          PORT: ${{ inputs.port }}
          APP_ENV: ${{ vars.APP_ENV }}
          APP_BASE_URL: ${{ vars.APP_BASE_URL }}
          APPLICATION_ID: ${{ secrets.APPLICATION_ID }}
          DB_FIX_TOKEN_SHA256: ${{ secrets.DB_FIX_TOKEN_SHA256 }}
          SKAUTIS_TEST_MODE: ${{ vars.SKAUTIS_TEST_MODE }}
          SEND_EMAIL: ${{ vars.SEND_EMAIL }}
          TEST_BACKGROUND: ${{ vars.TEST_BACKGROUND }}
          TRACY_SHOW_BAR: ${{ vars.TRACY_SHOW_BAR }}
          DB_HOST: ${{ vars.DB_HOST }}
          DB_NAME: ${{ vars.DB_NAME }}
          DB_USER: ${{ vars.DB_USER }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          GOOGLE_CREDENTIALS_FILE: ${{ vars.GOOGLE_CREDENTIALS_FILE }}
          GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
          SENTRY_DSN: ${{ secrets.SENTRY_DSN }}
          GITHUB_SHA: ${{ github.sha }}
